# ios/fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :release do
    # Incrementer le build number
    increment_build_number(
      xcodeproj: "BeaconSender.xcodeproj" # peut rester si increment_build_number nécessite le xcodeproj
    )

    # Build de l'app avec workspace CocoaPods
    build_app(
    workspace: "BeaconSender.xcworkspace",
    scheme: "BeaconSender",
    export_method: "app-store",
    archive_path: "./build/BeaconSender.xcarchive",
    export_options: {
        signingStyle: "automatic",
        teamID: ENV["APPLE_TEAM_ID"],
        provisioningProfiles: {
        "com.bertho.beaconsender" => "NomExactDuProfilAppStore"
        }
    },
    export_team_id: ENV["APPLE_TEAM_ID"],
    xcargs: "-allowProvisioningUpdates"
    )

    # Upload vers App Store Connect
    # upload_to_app_store(
    #   skip_metadata: true,
    #   skip_screenshots: true,
    #   ipa: "./build/app.ipa",
    #   force: true
    # )
  end

  desc "Build only (for testing)"
  lane :build_only do
    increment_build_number(
      xcodeproj: "BeaconSender.xcodeproj"
    )

    build_app(
    workspace: "BeaconSender.xcworkspace",
    scheme: "BeaconSender",
    export_method: "app-store",
    archive_path: "./build/BeaconSender.xcarchive",
    export_options: {
        signingStyle: "automatic",
        teamID: ENV["APPLE_TEAM_ID"],
        provisioningProfiles: {
        "com.bertho.beaconsender" => "NomExactDuProfilAppStore"
        }
    },
    export_team_id: ENV["APPLE_TEAM_ID"],
    xcargs: "-allowProvisioningUpdates"
    )
  end
end
